name: Deploy my lambda function

# trigger on all push events to main branch
on:
  push:
    branches:
      - main

#build job
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2      
        with:
          python-version: 3.11
      - name: Install  linting libraries
        run: | 
          cd function
          pip install pip==23.3.1
          pip install flask8=3.9.0
      - name: Lint with flask8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2        
        with:
          python-version: 3.8
      - name: Install libraries
        run: | 
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
          
      - name: Create zip bundle
        run: | 
          cd function
          zip -r ../${{ github.sha }}.zip .
          
      - name: Archieve artifact
        uses: actions/upload-artifact@v3
        with: 
          name: sp_artifact
          path: ${{ github.sha }}.zip  
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: 
          name: sp_artifact
          
        #send it to s3 bucket but before configure the key
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to s3
        run: aws s3 cp ${{ github.sha }}.zip  s3://my-bucket-sp1312/${{ github.sha }}.zip
  
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: update the function code
        run: | 
          aws lambda update-function-code \
            --function-name my-function \
            --s3-bucket my-bucket-sp1312 \
            --s3-key ${{ github.sha}}.zip \
            --publish
